import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "../components/Button";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ランチックス</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center flex-col min-h-screen">
        <p className="font-mono text-red-700">ランチックスを作るよ テスト</p>
        <Button
          label="ボタン"
          onClick={() => {
            alert("ボタンが押されました");
          }}
        />
        <Link href="/aaa/test">
          <a className="underline hover:text-blue-800 mt-3">リンクです</a>
        </Link>
      </main>
    </>
  );
};

export default Home;
